[logging]
level = "INFO"
file = "app.log"

[model_settings]
object_listing_model = "Qwen/Qwen2.5-VL-3B-Instruct" 
object_detection_model = "IDEA-Research/grounding-dino-base"
segmentation_model = "facebook/sam-vit-base"
description_model = "nvidia/DAM-3B-Self-Contained"
description_temperature = 0.2
description_top_p = 0.5
description_num_beams = 1
description_max_tokens = 512

[processing]
default_mode = "list_detect_segment_describe"
input_video_path = "sample_data/input.mp4"
output_directory = "output/"
frame_interval = 100

[visualization]
enabled = false
annotated_image_format = "jpg"
contour_enabled = false  # Enable contour visualization for segmentation
contour_thickness = 3   # Thickness of contour lines
description_viz_enabled = false  # Enable visualization with descriptions 