[logging]
level = "INFO"
file = "app.log"

[model_settings]
object_listing_model = "vikhyatk/moondream2" 
object_detection_model = "IDEA-Research/GroundingDINO-tiny"
segmentation_model = "facebook/sam-vit-base"
description_model = "nvidia/DAM-3B-Self-Contained"

[processing]
default_mode = "list"
input_video_path = "sample_data/input.mp4"
output_directory = "output/"
frame_interval = 100

[visualization]
enabled = true
annotated_image_format = "jpg" 